using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SportsStore.Migrations
{
    public partial class secondmigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Category",
                columns: table => new
                {
                    CategoryId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CategoryName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Category", x => x.CategoryId);
                });

            migrationBuilder.CreateTable(
                name: "ShoppingCarts",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductId = table.Column<int>(nullable: false),
                    OrderRegistrationDate = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ShoppingCarts", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Product",
                columns: table => new
                {
                    ProductId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductName = table.Column<string>(nullable: true),
                    Price = table.Column<decimal>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    CategoryName = table.Column<string>(nullable: true),
                    CategoryId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Product", x => x.ProductId);
                    table.ForeignKey(
                        name: "FK_Product_Category_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Category",
                        principalColumn: "CategoryId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ProductImages",
                columns: table => new
                {
                    ProductImageId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductID = table.Column<int>(nullable: false),
                    ImageUrl = table.Column<string>(nullable: true),
                    IsThumbnail = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductImages", x => x.ProductImageId);
                    table.ForeignKey(
                        name: "FK_ProductImages_Product_ProductID",
                        column: x => x.ProductID,
                        principalTable: "Product",
                        principalColumn: "ProductId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Category",
                columns: new[] { "CategoryId", "CategoryName" },
                values: new object[,]
                {
                    { 1, "Basketball" },
                    { 2, "Football" },
                    { 3, "LifeStyle" },
                    { 4, "baseball" },
                    { 5, "Running" }
                });

            migrationBuilder.InsertData(
                table: "Product",
                columns: new[] { "ProductId", "CategoryId", "CategoryName", "Description", "Price", "ProductName" },
                values: new object[,]
                {
                    { 3, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 3", 193m, "product 3" },
                    { 62, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 62", 2022m, "product 62" },
                    { 61, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 61", 1991m, "product 61" },
                    { 50, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 50", 1650m, "product 50" },
                    { 49, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 49", 1619m, "product 49" },
                    { 45, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 45", 1495m, "product 45" },
                    { 38, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 38", 1278m, "product 38" },
                    { 36, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 36", 1216m, "product 36" },
                    { 34, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 34", 1154m, "product 34" },
                    { 33, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 33", 1123m, "product 33" },
                    { 31, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 31", 1061m, "product 31" },
                    { 29, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 29", 999m, "product 29" },
                    { 25, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 25", 875m, "product 25" },
                    { 14, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 14", 534m, "product 14" },
                    { 9, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 9", 379m, "product 9" },
                    { 8, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 8", 348m, "product 8" },
                    { 2, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 2", 162m, "product 2" },
                    { 96, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 96", 3076m, "product 96" },
                    { 88, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 88", 2828m, "product 88" },
                    { 74, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 74", 2394m, "product 74" },
                    { 69, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 69", 2239m, "product 69" },
                    { 68, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 68", 2208m, "product 68" },
                    { 65, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 65", 2115m, "product 65" },
                    { 67, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 67", 2177m, "product 67" },
                    { 71, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 71", 2301m, "product 71" },
                    { 75, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 75", 2425m, "product 75" },
                    { 84, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 84", 2704m, "product 84" },
                    { 80, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 80", 2580m, "product 80" },
                    { 79, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 79", 2549m, "product 79" },
                    { 77, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 77", 2487m, "product 77" },
                    { 64, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 64", 2084m, "product 64" },
                    { 63, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 63", 2053m, "product 63" },
                    { 60, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 60", 1960m, "product 60" },
                    { 51, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 51", 1681m, "product 51" },
                    { 46, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 46", 1526m, "product 46" },
                    { 40, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 40", 1340m, "product 40" },
                    { 39, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 39", 1309m, "product 39" },
                    { 30, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 30", 1030m, "product 30" },
                    { 28, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 28", 968m, "product 28" },
                    { 20, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 20", 720m, "product 20" },
                    { 17, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 17", 627m, "product 17" },
                    { 15, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 15", 565m, "product 15" },
                    { 6, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 6", 286m, "product 6" },
                    { 5, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 5", 255m, "product 5" },
                    { 87, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 87", 2797m, "product 87" },
                    { 82, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 82", 2642m, "product 82" },
                    { 78, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 78", 2518m, "product 78" },
                    { 73, 4, "baseball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 73", 2363m, "product 73" },
                    { 66, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 66", 2146m, "product 66" },
                    { 59, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 59", 1929m, "product 59" },
                    { 58, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 58", 1898m, "product 58" },
                    { 42, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 42", 1402m, "product 42" },
                    { 41, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 41", 1371m, "product 41" },
                    { 35, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 35", 1185m, "product 35" },
                    { 19, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 19", 689m, "product 19" },
                    { 16, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 16", 596m, "product 16" },
                    { 12, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 12", 472m, "product 12" },
                    { 4, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 4", 224m, "product 4" },
                    { 95, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 95", 3045m, "product 95" },
                    { 94, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 94", 3014m, "product 94" },
                    { 93, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 93", 2983m, "product 93" },
                    { 92, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 92", 2952m, "product 92" },
                    { 85, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 85", 2735m, "product 85" },
                    { 81, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 81", 2611m, "product 81" },
                    { 47, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 47", 1557m, "product 47" },
                    { 43, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 43", 1433m, "product 43" },
                    { 32, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 32", 1092m, "product 32" },
                    { 27, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 27", 937m, "product 27" },
                    { 26, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 26", 906m, "product 26" },
                    { 23, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 23", 813m, "product 23" },
                    { 22, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 22", 782m, "product 22" },
                    { 13, 1, "Basketball", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 13", 503m, "product 13" },
                    { 52, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 52", 1712m, "product 52" },
                    { 53, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 53", 1743m, "product 53" },
                    { 54, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 54", 1774m, "product 54" },
                    { 70, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 70", 2270m, "product 70" },
                    { 57, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 57", 1867m, "product 57" },
                    { 56, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 56", 1836m, "product 56" },
                    { 55, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 55", 1805m, "product 55" },
                    { 48, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 48", 1588m, "product 48" },
                    { 44, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 44", 1464m, "product 44" },
                    { 37, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 37", 1247m, "product 37" },
                    { 24, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 24", 844m, "product 24" },
                    { 21, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 21", 751m, "product 21" },
                    { 18, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 18", 658m, "product 18" },
                    { 11, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 11", 441m, "product 11" },
                    { 90, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 90", 2890m, "product 90" },
                    { 10, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 10", 410m, "product 10" },
                    { 1, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 1", 131m, "product 1" },
                    { 100, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 100", 3200m, "product 100" },
                    { 98, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 98", 3138m, "product 98" },
                    { 97, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 97", 3107m, "product 97" },
                    { 91, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 91", 2921m, "product 91" },
                    { 89, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 89", 2859m, "product 89" },
                    { 86, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 86", 2766m, "product 86" },
                    { 83, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 83", 2673m, "product 83" },
                    { 76, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 76", 2456m, "product 76" },
                    { 72, 2, "Football", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 72", 2332m, "product 72" },
                    { 7, 3, "LifeStyle", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 7", 317m, "product 7" },
                    { 99, 5, "Running", "Reinvigorate your stride with the Nike Air Zoom Pegasus 37. Delivering the same fit and feel that runners love, the shoe has an all-new forefoot cushioning unit and foam for maximum responsiveness. The result is a durable, lightweight trainer designed for everyday running. 99", 3169m, "product 99" }
                });

            migrationBuilder.InsertData(
                table: "ProductImages",
                columns: new[] { "ProductImageId", "ImageUrl", "IsThumbnail", "ProductID" },
                values: new object[,]
                {
                    { 236, null, true, 3 },
                    { 103, null, true, 38 },
                    { 321, null, true, 36 },
                    { 314, null, true, 36 },
                    { 227, null, true, 36 },
                    { 176, null, true, 36 },
                    { 302, null, true, 34 },
                    { 277, null, true, 34 },
                    { 243, null, true, 34 },
                    { 140, null, true, 34 },
                    { 60, null, true, 34 },
                    { 208, null, true, 33 },
                    { 113, null, true, 33 },
                    { 100, null, true, 33 },
                    { 65, null, true, 33 },
                    { 57, null, true, 33 },
                    { 45, null, true, 33 },
                    { 282, null, true, 31 },
                    { 203, null, true, 31 },
                    { 47, null, true, 31 },
                    { 339, null, true, 29 },
                    { 297, null, true, 29 },
                    { 289, null, true, 38 },
                    { 155, null, true, 29 },
                    { 326, null, true, 38 },
                    { 93, null, true, 45 },
                    { 392, null, true, 62 },
                    { 189, null, true, 62 },
                    { 119, null, true, 62 },
                    { 21, null, true, 62 },
                    { 7, null, true, 62 },
                    { 351, null, true, 61 },
                    { 299, null, true, 61 },
                    { 293, null, true, 61 },
                    { 200, null, true, 61 },
                    { 122, null, true, 61 },
                    { 106, null, true, 61 },
                    { 55, null, true, 61 },
                    { 184, null, true, 50 },
                    { 175, null, true, 50 },
                    { 316, null, true, 49 },
                    { 254, null, true, 49 },
                    { 213, null, true, 49 },
                    { 152, null, true, 49 },
                    { 84, null, true, 49 },
                    { 393, null, true, 45 },
                    { 354, null, true, 45 },
                    { 346, null, true, 38 },
                    { 355, null, true, 65 },
                    { 108, null, true, 29 },
                    { 1, null, true, 29 },
                    { 178, null, true, 96 },
                    { 87, null, true, 96 },
                    { 62, null, true, 96 },
                    { 44, null, true, 96 },
                    { 38, null, true, 88 },
                    { 287, null, true, 74 },
                    { 188, null, true, 74 },
                    { 186, null, true, 74 },
                    { 120, null, true, 74 },
                    { 41, null, true, 74 },
                    { 76, null, true, 69 },
                    { 374, null, true, 68 },
                    { 201, null, true, 68 },
                    { 165, null, true, 68 },
                    { 142, null, true, 68 },
                    { 71, null, true, 68 },
                    { 273, null, true, 67 },
                    { 222, null, true, 67 },
                    { 214, null, true, 67 },
                    { 124, null, true, 67 },
                    { 359, null, true, 66 },
                    { 239, null, true, 96 },
                    { 77, null, true, 29 },
                    { 241, null, true, 96 },
                    { 310, null, true, 96 },
                    { 49, null, true, 25 },
                    { 298, null, true, 14 },
                    { 281, null, true, 14 },
                    { 242, null, true, 14 },
                    { 169, null, true, 14 },
                    { 51, null, true, 14 },
                    { 319, null, true, 9 },
                    { 279, null, true, 9 },
                    { 278, null, true, 9 },
                    { 251, null, true, 9 },
                    { 68, null, true, 9 },
                    { 30, null, true, 9 },
                    { 334, null, true, 8 },
                    { 180, null, true, 8 },
                    { 172, null, true, 8 },
                    { 22, null, true, 8 },
                    { 313, null, true, 2 },
                    { 300, null, true, 2 },
                    { 89, null, true, 2 },
                    { 371, null, true, 96 },
                    { 331, null, true, 96 },
                    { 253, null, true, 96 },
                    { 13, null, true, 71 },
                    { 173, null, true, 71 },
                    { 225, null, true, 71 },
                    { 325, null, true, 60 },
                    { 234, null, true, 60 },
                    { 153, null, true, 60 },
                    { 94, null, true, 60 },
                    { 75, null, true, 60 },
                    { 382, null, true, 51 },
                    { 46, null, true, 51 },
                    { 375, null, true, 46 },
                    { 219, null, true, 46 },
                    { 187, null, true, 46 },
                    { 160, null, true, 46 },
                    { 97, null, true, 46 },
                    { 290, null, true, 40 },
                    { 235, null, true, 40 },
                    { 209, null, true, 40 },
                    { 128, null, true, 40 },
                    { 81, null, true, 40 },
                    { 29, null, true, 40 },
                    { 329, null, true, 39 },
                    { 283, null, true, 39 },
                    { 272, null, true, 39 },
                    { 34, null, true, 63 },
                    { 221, null, true, 39 },
                    { 133, null, true, 63 },
                    { 335, null, true, 63 },
                    { 228, null, true, 90 },
                    { 50, null, true, 90 },
                    { 294, null, true, 80 },
                    { 195, null, true, 80 },
                    { 194, null, true, 80 },
                    { 82, null, true, 80 },
                    { 367, null, true, 79 },
                    { 336, null, true, 79 },
                    { 261, null, true, 79 },
                    { 223, null, true, 79 },
                    { 43, null, true, 79 },
                    { 15, null, true, 79 },
                    { 349, null, true, 77 },
                    { 327, null, true, 77 },
                    { 364, null, true, 64 },
                    { 295, null, true, 64 },
                    { 267, null, true, 64 },
                    { 218, null, true, 64 },
                    { 150, null, true, 64 },
                    { 99, null, true, 64 },
                    { 356, null, true, 63 },
                    { 182, null, true, 63 },
                    { 90, null, true, 39 },
                    { 305, null, true, 30 },
                    { 196, null, true, 30 },
                    { 5, null, true, 5 },
                    { 330, null, true, 87 },
                    { 328, null, true, 87 },
                    { 324, null, true, 87 },
                    { 262, null, true, 87 },
                    { 135, null, true, 87 },
                    { 109, null, true, 87 },
                    { 357, null, true, 82 },
                    { 238, null, true, 82 },
                    { 231, null, true, 82 },
                    { 130, null, true, 82 },
                    { 33, null, true, 82 },
                    { 303, null, true, 78 },
                    { 207, null, true, 78 },
                    { 96, null, true, 78 },
                    { 19, null, true, 78 },
                    { 12, null, true, 78 },
                    { 170, null, true, 75 },
                    { 159, null, true, 75 },
                    { 345, null, true, 73 },
                    { 183, null, true, 73 },
                    { 121, null, true, 5 },
                    { 191, null, true, 5 },
                    { 377, null, true, 5 },
                    { 112, null, true, 6 },
                    { 74, null, true, 30 },
                    { 312, null, true, 28 },
                    { 215, null, true, 28 },
                    { 174, null, true, 28 },
                    { 347, null, true, 20 },
                    { 332, null, true, 20 },
                    { 264, null, true, 20 },
                    { 230, null, true, 20 },
                    { 320, null, true, 17 },
                    { 260, null, true, 17 },
                    { 311, null, true, 66 },
                    { 387, null, true, 15 },
                    { 350, null, true, 15 },
                    { 206, null, true, 15 },
                    { 163, null, true, 15 },
                    { 157, null, true, 15 },
                    { 129, null, true, 15 },
                    { 91, null, true, 15 },
                    { 353, null, true, 6 },
                    { 288, null, true, 6 },
                    { 248, null, true, 6 },
                    { 164, null, true, 6 },
                    { 379, null, true, 15 },
                    { 358, null, true, 90 },
                    { 291, null, true, 66 },
                    { 28, null, true, 66 },
                    { 202, null, true, 16 },
                    { 95, null, true, 16 },
                    { 16, null, true, 16 },
                    { 338, null, true, 12 },
                    { 245, null, true, 12 },
                    { 388, null, true, 4 },
                    { 85, null, true, 95 },
                    { 67, null, true, 95 },
                    { 368, null, true, 94 },
                    { 162, null, true, 94 },
                    { 156, null, true, 94 },
                    { 39, null, true, 94 },
                    { 18, null, true, 94 },
                    { 386, null, true, 93 },
                    { 361, null, true, 93 },
                    { 308, null, true, 93 },
                    { 286, null, true, 93 },
                    { 220, null, true, 93 },
                    { 190, null, true, 93 },
                    { 115, null, true, 93 },
                    { 31, null, true, 93 },
                    { 136, null, true, 19 },
                    { 25, null, true, 93 },
                    { 181, null, true, 19 },
                    { 52, null, true, 35 },
                    { 161, null, true, 54 },
                    { 337, null, true, 53 },
                    { 323, null, true, 52 },
                    { 309, null, true, 52 },
                    { 249, null, true, 52 },
                    { 116, null, true, 52 },
                    { 72, null, true, 52 },
                    { 389, null, true, 42 },
                    { 199, null, true, 42 },
                    { 168, null, true, 42 },
                    { 167, null, true, 42 },
                    { 137, null, true, 42 },
                    { 399, null, true, 41 },
                    { 344, null, true, 41 },
                    { 340, null, true, 41 },
                    { 83, null, true, 41 },
                    { 17, null, true, 41 },
                    { 396, null, true, 35 },
                    { 362, null, true, 35 },
                    { 107, null, true, 35 },
                    { 88, null, true, 35 },
                    { 20, null, true, 35 },
                    { 197, null, true, 54 },
                    { 360, null, true, 92 },
                    { 111, null, true, 92 },
                    { 10, null, true, 27 },
                    { 385, null, true, 26 },
                    { 348, null, true, 26 },
                    { 276, null, true, 26 },
                    { 270, null, true, 26 },
                    { 370, null, true, 23 },
                    { 307, null, true, 23 },
                    { 151, null, true, 23 },
                    { 131, null, true, 23 },
                    { 105, null, true, 23 },
                    { 380, null, true, 22 },
                    { 301, null, true, 22 },
                    { 292, null, true, 22 },
                    { 255, null, true, 22 },
                    { 102, null, true, 22 },
                    { 98, null, true, 22 },
                    { 177, null, true, 13 },
                    { 3, null, true, 13 },
                    { 352, null, true, 3 },
                    { 315, null, true, 3 },
                    { 274, null, true, 3 },
                    { 78, null, true, 27 },
                    { 210, null, true, 92 },
                    { 139, null, true, 27 },
                    { 304, null, true, 27 },
                    { 104, null, true, 92 },
                    { 42, null, true, 92 },
                    { 280, null, true, 85 },
                    { 263, null, true, 85 },
                    { 166, null, true, 85 },
                    { 342, null, true, 81 },
                    { 211, null, true, 81 },
                    { 395, null, true, 47 },
                    { 366, null, true, 47 },
                    { 229, null, true, 47 },
                    { 145, null, true, 47 },
                    { 63, null, true, 47 },
                    { 36, null, true, 47 },
                    { 198, null, true, 43 },
                    { 80, null, true, 43 },
                    { 237, null, true, 32 },
                    { 70, null, true, 32 },
                    { 61, null, true, 32 },
                    { 400, null, true, 27 },
                    { 397, null, true, 27 },
                    { 318, null, true, 27 },
                    { 269, null, true, 27 },
                    { 205, null, true, 54 },
                    { 233, null, true, 54 },
                    { 343, null, true, 54 },
                    { 138, null, true, 48 },
                    { 54, null, true, 48 },
                    { 40, null, true, 48 },
                    { 37, null, true, 48 },
                    { 240, null, true, 44 },
                    { 148, null, true, 44 },
                    { 59, null, true, 44 },
                    { 48, null, true, 44 },
                    { 394, null, true, 37 },
                    { 372, null, true, 37 },
                    { 257, null, true, 37 },
                    { 226, null, true, 37 },
                    { 4, null, true, 37 },
                    { 384, null, true, 24 },
                    { 247, null, true, 24 },
                    { 141, null, true, 24 },
                    { 79, null, true, 24 },
                    { 27, null, true, 24 },
                    { 23, null, true, 24 },
                    { 259, null, true, 21 },
                    { 224, null, true, 21 },
                    { 143, null, true, 48 },
                    { 217, null, true, 21 },
                    { 317, null, true, 48 },
                    { 11, null, true, 55 },
                    { 14, null, true, 66 },
                    { 9, null, true, 66 },
                    { 271, null, true, 59 },
                    { 185, null, true, 59 },
                    { 86, null, true, 59 },
                    { 35, null, true, 59 },
                    { 401, null, true, 58 },
                    { 322, null, true, 58 },
                    { 284, null, true, 58 },
                    { 147, null, true, 58 },
                    { 53, null, true, 58 },
                    { 64, null, true, 57 },
                    { 58, null, true, 57 },
                    { 24, null, true, 56 },
                    { 6, null, true, 56 },
                    { 2, null, true, 56 },
                    { 376, null, true, 55 },
                    { 363, null, true, 55 },
                    { 117, null, true, 55 },
                    { 101, null, true, 55 },
                    { 32, null, true, 55 },
                    { 333, null, true, 48 },
                    { 179, null, true, 21 },
                    { 56, null, true, 21 },
                    { 381, null, true, 18 },
                    { 204, null, true, 91 },
                    { 134, null, true, 91 },
                    { 110, null, true, 91 },
                    { 92, null, true, 91 },
                    { 398, null, true, 89 },
                    { 268, null, true, 89 },
                    { 252, null, true, 89 },
                    { 250, null, true, 89 },
                    { 154, null, true, 89 },
                    { 246, null, true, 86 },
                    { 8, null, true, 86 },
                    { 126, null, true, 76 },
                    { 369, null, true, 72 },
                    { 193, null, true, 72 },
                    { 192, null, true, 72 },
                    { 341, null, true, 70 },
                    { 306, null, true, 70 },
                    { 244, null, true, 70 },
                    { 232, null, true, 70 },
                    { 158, null, true, 70 },
                    { 26, null, true, 70 },
                    { 216, null, true, 91 },
                    { 118, null, true, 97 },
                    { 275, null, true, 97 },
                    { 373, null, true, 97 },
                    { 212, null, true, 18 },
                    { 125, null, true, 18 },
                    { 378, null, true, 11 },
                    { 285, null, true, 11 },
                    { 266, null, true, 11 },
                    { 258, null, true, 11 },
                    { 144, null, true, 11 },
                    { 383, null, true, 10 },
                    { 296, null, true, 10 },
                    { 265, null, true, 10 },
                    { 149, null, true, 66 },
                    { 171, null, true, 10 },
                    { 132, null, true, 7 },
                    { 127, null, true, 7 },
                    { 123, null, true, 7 },
                    { 69, null, true, 7 },
                    { 365, null, true, 1 },
                    { 256, null, true, 1 },
                    { 114, null, true, 1 },
                    { 73, null, true, 1 },
                    { 66, null, true, 1 },
                    { 391, null, true, 97 },
                    { 146, null, true, 10 },
                    { 390, null, true, 99 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Product_CategoryId",
                table: "Product",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductImages_ProductID",
                table: "ProductImages",
                column: "ProductID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProductImages");

            migrationBuilder.DropTable(
                name: "ShoppingCarts");

            migrationBuilder.DropTable(
                name: "Product");

            migrationBuilder.DropTable(
                name: "Category");
        }
    }
}
