using Microsoft.EntityFrameworkCore.Migrations;

namespace SportsStore.Migrations
{
    public partial class firstMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Category",
                columns: table => new
                {
                    CategoryId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CategoryName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Category", x => x.CategoryId);
                });

            migrationBuilder.CreateTable(
                name: "Product",
                columns: table => new
                {
                    ProductId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductName = table.Column<string>(nullable: true),
                    Price = table.Column<decimal>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    CategoryName = table.Column<string>(nullable: true),
                    CategoryId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Product", x => x.ProductId);
                    table.ForeignKey(
                        name: "FK_Product_Category_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Category",
                        principalColumn: "CategoryId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ProductImages",
                columns: table => new
                {
                    ProductImageId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductID = table.Column<int>(nullable: false),
                    ImageUrl = table.Column<string>(nullable: true),
                    IsThumbnail = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductImages", x => x.ProductImageId);
                    table.ForeignKey(
                        name: "FK_ProductImages_Product_ProductID",
                        column: x => x.ProductID,
                        principalTable: "Product",
                        principalColumn: "ProductId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Category",
                columns: new[] { "CategoryId", "CategoryName" },
                values: new object[,]
                {
                    { 1, "Basketball" },
                    { 2, "Football" },
                    { 3, "LifeStyle" },
                    { 4, "baseball" },
                    { 5, "Running" }
                });

            migrationBuilder.InsertData(
                table: "Product",
                columns: new[] { "ProductId", "CategoryId", "CategoryName", "Description", "Price", "ProductName" },
                values: new object[,]
                {
                    { 2, 1, "Basketball", "blabla 2", 162m, "product 2" },
                    { 11, 4, "baseball", "blabla 11", 441m, "product 11" },
                    { 10, 4, "baseball", "blabla 10", 410m, "product 10" },
                    { 99, 3, "LifeStyle", "blabla 99", 3169m, "product 99" },
                    { 96, 3, "LifeStyle", "blabla 96", 3076m, "product 96" },
                    { 95, 3, "LifeStyle", "blabla 95", 3045m, "product 95" },
                    { 91, 3, "LifeStyle", "blabla 91", 2921m, "product 91" },
                    { 85, 3, "LifeStyle", "blabla 85", 2735m, "product 85" },
                    { 82, 3, "LifeStyle", "blabla 82", 2642m, "product 82" },
                    { 79, 3, "LifeStyle", "blabla 79", 2549m, "product 79" },
                    { 73, 3, "LifeStyle", "blabla 73", 2363m, "product 73" },
                    { 72, 3, "LifeStyle", "blabla 72", 2332m, "product 72" },
                    { 71, 3, "LifeStyle", "blabla 71", 2301m, "product 71" },
                    { 67, 3, "LifeStyle", "blabla 67", 2177m, "product 67" },
                    { 64, 3, "LifeStyle", "blabla 64", 2084m, "product 64" },
                    { 63, 3, "LifeStyle", "blabla 63", 2053m, "product 63" },
                    { 58, 3, "LifeStyle", "blabla 58", 1898m, "product 58" },
                    { 57, 3, "LifeStyle", "blabla 57", 1867m, "product 57" },
                    { 48, 3, "LifeStyle", "blabla 48", 1588m, "product 48" },
                    { 47, 3, "LifeStyle", "blabla 47", 1557m, "product 47" },
                    { 44, 3, "LifeStyle", "blabla 44", 1464m, "product 44" },
                    { 42, 3, "LifeStyle", "blabla 42", 1402m, "product 42" },
                    { 13, 4, "baseball", "blabla 13", 503m, "product 13" },
                    { 40, 3, "LifeStyle", "blabla 40", 1340m, "product 40" },
                    { 19, 4, "baseball", "blabla 19", 689m, "product 19" },
                    { 24, 4, "baseball", "blabla 24", 844m, "product 24" },
                    { 92, 5, "Running", "blabla 92", 2952m, "product 92" },
                    { 88, 5, "Running", "blabla 88", 2828m, "product 88" },
                    { 76, 5, "Running", "blabla 76", 2456m, "product 76" },
                    { 66, 5, "Running", "blabla 66", 2146m, "product 66" },
                    { 62, 5, "Running", "blabla 62", 2022m, "product 62" },
                    { 56, 5, "Running", "blabla 56", 1836m, "product 56" },
                    { 43, 5, "Running", "blabla 43", 1433m, "product 43" },
                    { 38, 5, "Running", "blabla 38", 1278m, "product 38" },
                    { 36, 5, "Running", "blabla 36", 1216m, "product 36" },
                    { 33, 5, "Running", "blabla 33", 1123m, "product 33" },
                    { 30, 5, "Running", "blabla 30", 1030m, "product 30" },
                    { 26, 5, "Running", "blabla 26", 906m, "product 26" },
                    { 16, 5, "Running", "blabla 16", 596m, "product 16" },
                    { 14, 5, "Running", "blabla 14", 534m, "product 14" },
                    { 86, 4, "baseball", "blabla 86", 2766m, "product 86" },
                    { 77, 4, "baseball", "blabla 77", 2487m, "product 77" },
                    { 69, 4, "baseball", "blabla 69", 2239m, "product 69" },
                    { 60, 4, "baseball", "blabla 60", 1960m, "product 60" },
                    { 32, 4, "baseball", "blabla 32", 1092m, "product 32" },
                    { 31, 4, "baseball", "blabla 31", 1061m, "product 31" },
                    { 29, 4, "baseball", "blabla 29", 999m, "product 29" },
                    { 23, 4, "baseball", "blabla 23", 813m, "product 23" },
                    { 34, 3, "LifeStyle", "blabla 34", 1154m, "product 34" },
                    { 25, 3, "LifeStyle", "blabla 25", 875m, "product 25" },
                    { 22, 3, "LifeStyle", "blabla 22", 782m, "product 22" },
                    { 20, 2, "Football", "blabla 20", 720m, "product 20" },
                    { 15, 2, "Football", "blabla 15", 565m, "product 15" },
                    { 12, 2, "Football", "blabla 12", 472m, "product 12" },
                    { 8, 2, "Football", "blabla 8", 348m, "product 8" },
                    { 7, 2, "Football", "blabla 7", 317m, "product 7" },
                    { 3, 2, "Football", "blabla 3", 193m, "product 3" },
                    { 1, 2, "Football", "blabla 1", 131m, "product 1" },
                    { 83, 1, "Basketball", "blabla 83", 2673m, "product 83" },
                    { 78, 1, "Basketball", "blabla 78", 2518m, "product 78" },
                    { 75, 1, "Basketball", "blabla 75", 2425m, "product 75" },
                    { 68, 1, "Basketball", "blabla 68", 2208m, "product 68" },
                    { 65, 1, "Basketball", "blabla 65", 2115m, "product 65" },
                    { 61, 1, "Basketball", "blabla 61", 1991m, "product 61" },
                    { 59, 1, "Basketball", "blabla 59", 1929m, "product 59" },
                    { 54, 1, "Basketball", "blabla 54", 1774m, "product 54" },
                    { 52, 1, "Basketball", "blabla 52", 1712m, "product 52" },
                    { 46, 1, "Basketball", "blabla 46", 1526m, "product 46" },
                    { 39, 1, "Basketball", "blabla 39", 1309m, "product 39" },
                    { 35, 1, "Basketball", "blabla 35", 1185m, "product 35" },
                    { 27, 1, "Basketball", "blabla 27", 937m, "product 27" },
                    { 6, 1, "Basketball", "blabla 6", 286m, "product 6" },
                    { 21, 2, "Football", "blabla 21", 751m, "product 21" },
                    { 28, 2, "Football", "blabla 28", 968m, "product 28" },
                    { 37, 2, "Football", "blabla 37", 1247m, "product 37" },
                    { 41, 2, "Football", "blabla 41", 1371m, "product 41" },
                    { 18, 3, "LifeStyle", "blabla 18", 658m, "product 18" },
                    { 17, 3, "LifeStyle", "blabla 17", 627m, "product 17" },
                    { 9, 3, "LifeStyle", "blabla 9", 379m, "product 9" },
                    { 5, 3, "LifeStyle", "blabla 5", 255m, "product 5" },
                    { 4, 3, "LifeStyle", "blabla 4", 224m, "product 4" },
                    { 100, 2, "Football", "blabla 100", 3200m, "product 100" },
                    { 98, 2, "Football", "blabla 98", 3138m, "product 98" },
                    { 94, 2, "Football", "blabla 94", 3014m, "product 94" },
                    { 90, 2, "Football", "blabla 90", 2890m, "product 90" },
                    { 89, 2, "Football", "blabla 89", 2859m, "product 89" },
                    { 93, 5, "Running", "blabla 93", 2983m, "product 93" },
                    { 87, 2, "Football", "blabla 87", 2797m, "product 87" },
                    { 81, 2, "Football", "blabla 81", 2611m, "product 81" },
                    { 80, 2, "Football", "blabla 80", 2580m, "product 80" },
                    { 74, 2, "Football", "blabla 74", 2394m, "product 74" },
                    { 70, 2, "Football", "blabla 70", 2270m, "product 70" },
                    { 55, 2, "Football", "blabla 55", 1805m, "product 55" },
                    { 53, 2, "Football", "blabla 53", 1743m, "product 53" },
                    { 51, 2, "Football", "blabla 51", 1681m, "product 51" },
                    { 50, 2, "Football", "blabla 50", 1650m, "product 50" },
                    { 49, 2, "Football", "blabla 49", 1619m, "product 49" },
                    { 45, 2, "Football", "blabla 45", 1495m, "product 45" },
                    { 84, 2, "Football", "blabla 84", 2704m, "product 84" },
                    { 97, 5, "Running", "blabla 97", 3107m, "product 97" }
                });

            migrationBuilder.InsertData(
                table: "ProductImages",
                columns: new[] { "ProductImageId", "ImageUrl", "IsThumbnail", "ProductID" },
                values: new object[,]
                {
                    { 266, "https://via.placeholder.com/150", true, 2 },
                    { 368, "https://via.placeholder.com/150", true, 10 },
                    { 289, "https://via.placeholder.com/150", true, 99 },
                    { 271, "https://via.placeholder.com/150", true, 99 },
                    { 361, "https://via.placeholder.com/150", true, 96 },
                    { 339, "https://via.placeholder.com/150", true, 96 },
                    { 277, "https://via.placeholder.com/150", true, 96 },
                    { 243, "https://via.placeholder.com/150", true, 96 },
                    { 102, "https://via.placeholder.com/150", true, 96 },
                    { 44, "https://via.placeholder.com/150", true, 96 },
                    { 376, "https://via.placeholder.com/150", true, 95 },
                    { 338, "https://via.placeholder.com/150", true, 95 },
                    { 125, "https://via.placeholder.com/150", true, 95 },
                    { 85, "https://via.placeholder.com/150", true, 95 },
                    { 69, "https://via.placeholder.com/150", true, 95 },
                    { 36, "https://via.placeholder.com/150", true, 95 },
                    { 394, "https://via.placeholder.com/150", true, 91 },
                    { 186, "https://via.placeholder.com/150", true, 91 },
                    { 66, "https://via.placeholder.com/150", true, 91 },
                    { 3, "https://via.placeholder.com/150", true, 91 },
                    { 350, "https://via.placeholder.com/150", true, 85 },
                    { 294, "https://via.placeholder.com/150", true, 85 },
                    { 382, "https://via.placeholder.com/150", true, 11 },
                    { 284, "https://via.placeholder.com/150", true, 85 },
                    { 41, "https://via.placeholder.com/150", true, 13 },
                    { 100, "https://via.placeholder.com/150", true, 13 },
                    { 111, "https://via.placeholder.com/150", true, 29 },
                    { 175, "https://via.placeholder.com/150", true, 24 },
                    { 133, "https://via.placeholder.com/150", true, 24 },
                    { 82, "https://via.placeholder.com/150", true, 24 },
                    { 370, "https://via.placeholder.com/150", true, 23 },
                    { 359, "https://via.placeholder.com/150", true, 23 },
                    { 219, "https://via.placeholder.com/150", true, 23 },
                    { 182, "https://via.placeholder.com/150", true, 23 },
                    { 134, "https://via.placeholder.com/150", true, 23 },
                    { 61, "https://via.placeholder.com/150", true, 23 },
                    { 388, "https://via.placeholder.com/150", true, 19 },
                    { 384, "https://via.placeholder.com/150", true, 19 },
                    { 358, "https://via.placeholder.com/150", true, 19 },
                    { 324, "https://via.placeholder.com/150", true, 19 },
                    { 272, "https://via.placeholder.com/150", true, 19 },
                    { 252, "https://via.placeholder.com/150", true, 19 },
                    { 42, "https://via.placeholder.com/150", true, 19 },
                    { 364, "https://via.placeholder.com/150", true, 13 },
                    { 171, "https://via.placeholder.com/150", true, 13 },
                    { 163, "https://via.placeholder.com/150", true, 13 },
                    { 161, "https://via.placeholder.com/150", true, 13 },
                    { 84, "https://via.placeholder.com/150", true, 13 },
                    { 155, "https://via.placeholder.com/150", true, 29 },
                    { 217, "https://via.placeholder.com/150", true, 85 },
                    { 190, "https://via.placeholder.com/150", true, 82 },
                    { 255, "https://via.placeholder.com/150", true, 63 },
                    { 234, "https://via.placeholder.com/150", true, 63 },
                    { 173, "https://via.placeholder.com/150", true, 63 },
                    { 90, "https://via.placeholder.com/150", true, 63 },
                    { 21, "https://via.placeholder.com/150", true, 63 },
                    { 262, "https://via.placeholder.com/150", true, 58 },
                    { 131, "https://via.placeholder.com/150", true, 58 },
                    { 301, "https://via.placeholder.com/150", true, 57 },
                    { 281, "https://via.placeholder.com/150", true, 57 },
                    { 224, "https://via.placeholder.com/150", true, 57 },
                    { 139, "https://via.placeholder.com/150", true, 57 },
                    { 67, "https://via.placeholder.com/150", true, 57 },
                    { 27, "https://via.placeholder.com/150", true, 57 },
                    { 322, "https://via.placeholder.com/150", true, 48 },
                    { 290, "https://via.placeholder.com/150", true, 48 },
                    { 191, "https://via.placeholder.com/150", true, 48 },
                    { 188, "https://via.placeholder.com/150", true, 48 },
                    { 365, "https://via.placeholder.com/150", true, 44 },
                    { 323, "https://via.placeholder.com/150", true, 44 },
                    { 299, "https://via.placeholder.com/150", true, 44 },
                    { 268, "https://via.placeholder.com/150", true, 44 },
                    { 363, "https://via.placeholder.com/150", true, 63 },
                    { 47, "https://via.placeholder.com/150", true, 85 },
                    { 72, "https://via.placeholder.com/150", true, 64 },
                    { 25, "https://via.placeholder.com/150", true, 67 },
                    { 392, "https://via.placeholder.com/150", true, 79 },
                    { 293, "https://via.placeholder.com/150", true, 79 },
                    { 156, "https://via.placeholder.com/150", true, 79 },
                    { 371, "https://via.placeholder.com/150", true, 73 },
                    { 343, "https://via.placeholder.com/150", true, 73 },
                    { 229, "https://via.placeholder.com/150", true, 73 },
                    { 393, "https://via.placeholder.com/150", true, 72 },
                    { 390, "https://via.placeholder.com/150", true, 72 },
                    { 221, "https://via.placeholder.com/150", true, 72 },
                    { 55, "https://via.placeholder.com/150", true, 72 },
                    { 40, "https://via.placeholder.com/150", true, 72 },
                    { 26, "https://via.placeholder.com/150", true, 72 },
                    { 17, "https://via.placeholder.com/150", true, 72 },
                    { 316, "https://via.placeholder.com/150", true, 71 },
                    { 309, "https://via.placeholder.com/150", true, 71 },
                    { 104, "https://via.placeholder.com/150", true, 71 },
                    { 93, "https://via.placeholder.com/150", true, 71 },
                    { 50, "https://via.placeholder.com/150", true, 71 },
                    { 383, "https://via.placeholder.com/150", true, 67 },
                    { 308, "https://via.placeholder.com/150", true, 67 },
                    { 269, "https://via.placeholder.com/150", true, 67 },
                    { 232, "https://via.placeholder.com/150", true, 64 },
                    { 167, "https://via.placeholder.com/150", true, 42 },
                    { 285, "https://via.placeholder.com/150", true, 29 },
                    { 46, "https://via.placeholder.com/150", true, 31 },
                    { 295, "https://via.placeholder.com/150", true, 56 },
                    { 208, "https://via.placeholder.com/150", true, 56 },
                    { 311, "https://via.placeholder.com/150", true, 43 },
                    { 157, "https://via.placeholder.com/150", true, 43 },
                    { 151, "https://via.placeholder.com/150", true, 43 },
                    { 303, "https://via.placeholder.com/150", true, 38 },
                    { 205, "https://via.placeholder.com/150", true, 38 },
                    { 103, "https://via.placeholder.com/150", true, 38 },
                    { 62, "https://via.placeholder.com/150", true, 38 },
                    { 306, "https://via.placeholder.com/150", true, 36 },
                    { 200, "https://via.placeholder.com/150", true, 36 },
                    { 89, "https://via.placeholder.com/150", true, 36 },
                    { 80, "https://via.placeholder.com/150", true, 36 },
                    { 64, "https://via.placeholder.com/150", true, 36 },
                    { 201, "https://via.placeholder.com/150", true, 33 },
                    { 124, "https://via.placeholder.com/150", true, 33 },
                    { 48, "https://via.placeholder.com/150", true, 33 },
                    { 32, "https://via.placeholder.com/150", true, 33 },
                    { 307, "https://via.placeholder.com/150", true, 30 },
                    { 296, "https://via.placeholder.com/150", true, 30 },
                    { 18, "https://via.placeholder.com/150", true, 30 },
                    { 88, "https://via.placeholder.com/150", true, 62 },
                    { 372, "https://via.placeholder.com/150", true, 26 },
                    { 135, "https://via.placeholder.com/150", true, 62 },
                    { 1, "https://via.placeholder.com/150", true, 66 },
                    { 318, "https://via.placeholder.com/150", true, 97 },
                    { 172, "https://via.placeholder.com/150", true, 97 },
                    { 166, "https://via.placeholder.com/150", true, 97 },
                    { 340, "https://via.placeholder.com/150", true, 93 },
                    { 222, "https://via.placeholder.com/150", true, 93 },
                    { 189, "https://via.placeholder.com/150", true, 93 },
                    { 168, "https://via.placeholder.com/150", true, 93 },
                    { 127, "https://via.placeholder.com/150", true, 93 },
                    { 380, "https://via.placeholder.com/150", true, 92 },
                    { 267, "https://via.placeholder.com/150", true, 92 },
                    { 239, "https://via.placeholder.com/150", true, 92 },
                    { 353, "https://via.placeholder.com/150", true, 88 },
                    { 352, "https://via.placeholder.com/150", true, 88 },
                    { 305, "https://via.placeholder.com/150", true, 88 },
                    { 241, "https://via.placeholder.com/150", true, 88 },
                    { 78, "https://via.placeholder.com/150", true, 88 },
                    { 278, "https://via.placeholder.com/150", true, 66 },
                    { 238, "https://via.placeholder.com/150", true, 66 },
                    { 152, "https://via.placeholder.com/150", true, 66 },
                    { 141, "https://via.placeholder.com/150", true, 66 },
                    { 112, "https://via.placeholder.com/150", true, 66 },
                    { 240, "https://via.placeholder.com/150", true, 62 },
                    { 348, "https://via.placeholder.com/150", true, 29 },
                    { 362, "https://via.placeholder.com/150", true, 26 },
                    { 334, "https://via.placeholder.com/150", true, 26 },
                    { 231, "https://via.placeholder.com/150", true, 69 },
                    { 165, "https://via.placeholder.com/150", true, 69 },
                    { 35, "https://via.placeholder.com/150", true, 69 },
                    { 33, "https://via.placeholder.com/150", true, 69 },
                    { 16, "https://via.placeholder.com/150", true, 69 },
                    { 310, "https://via.placeholder.com/150", true, 60 },
                    { 274, "https://via.placeholder.com/150", true, 60 },
                    { 400, "https://via.placeholder.com/150", true, 32 },
                    { 226, "https://via.placeholder.com/150", true, 32 },
                    { 203, "https://via.placeholder.com/150", true, 32 },
                    { 132, "https://via.placeholder.com/150", true, 32 },
                    { 117, "https://via.placeholder.com/150", true, 32 },
                    { 63, "https://via.placeholder.com/150", true, 32 },
                    { 15, "https://via.placeholder.com/150", true, 32 },
                    { 10, "https://via.placeholder.com/150", true, 32 },
                    { 302, "https://via.placeholder.com/150", true, 31 },
                    { 184, "https://via.placeholder.com/150", true, 31 },
                    { 181, "https://via.placeholder.com/150", true, 31 },
                    { 164, "https://via.placeholder.com/150", true, 31 },
                    { 74, "https://via.placeholder.com/150", true, 31 },
                    { 65, "https://via.placeholder.com/150", true, 31 },
                    { 242, "https://via.placeholder.com/150", true, 69 },
                    { 346, "https://via.placeholder.com/150", true, 26 },
                    { 332, "https://via.placeholder.com/150", true, 69 },
                    { 369, "https://via.placeholder.com/150", true, 69 },
                    { 187, "https://via.placeholder.com/150", true, 26 },
                    { 162, "https://via.placeholder.com/150", true, 26 },
                    { 115, "https://via.placeholder.com/150", true, 26 },
                    { 75, "https://via.placeholder.com/150", true, 26 },
                    { 53, "https://via.placeholder.com/150", true, 26 },
                    { 12, "https://via.placeholder.com/150", true, 26 },
                    { 292, "https://via.placeholder.com/150", true, 16 },
                    { 126, "https://via.placeholder.com/150", true, 16 },
                    { 8, "https://via.placeholder.com/150", true, 16 },
                    { 379, "https://via.placeholder.com/150", true, 14 },
                    { 142, "https://via.placeholder.com/150", true, 14 },
                    { 28, "https://via.placeholder.com/150", true, 14 },
                    { 357, "https://via.placeholder.com/150", true, 86 },
                    { 297, "https://via.placeholder.com/150", true, 86 },
                    { 225, "https://via.placeholder.com/150", true, 86 },
                    { 137, "https://via.placeholder.com/150", true, 86 },
                    { 97, "https://via.placeholder.com/150", true, 86 },
                    { 81, "https://via.placeholder.com/150", true, 86 },
                    { 220, "https://via.placeholder.com/150", true, 77 },
                    { 195, "https://via.placeholder.com/150", true, 77 },
                    { 77, "https://via.placeholder.com/150", true, 77 },
                    { 342, "https://via.placeholder.com/150", true, 69 },
                    { 86, "https://via.placeholder.com/150", true, 42 },
                    { 327, "https://via.placeholder.com/150", true, 40 },
                    { 320, "https://via.placeholder.com/150", true, 40 },
                    { 49, "https://via.placeholder.com/150", true, 8 },
                    { 38, "https://via.placeholder.com/150", true, 8 },
                    { 397, "https://via.placeholder.com/150", true, 7 },
                    { 261, "https://via.placeholder.com/150", true, 7 },
                    { 260, "https://via.placeholder.com/150", true, 7 },
                    { 213, "https://via.placeholder.com/150", true, 7 },
                    { 153, "https://via.placeholder.com/150", true, 7 },
                    { 56, "https://via.placeholder.com/150", true, 7 },
                    { 367, "https://via.placeholder.com/150", true, 3 },
                    { 276, "https://via.placeholder.com/150", true, 3 },
                    { 19, "https://via.placeholder.com/150", true, 3 },
                    { 223, "https://via.placeholder.com/150", true, 1 },
                    { 197, "https://via.placeholder.com/150", true, 1 },
                    { 114, "https://via.placeholder.com/150", true, 1 },
                    { 92, "https://via.placeholder.com/150", true, 1 },
                    { 31, "https://via.placeholder.com/150", true, 1 },
                    { 9, "https://via.placeholder.com/150", true, 1 },
                    { 326, "https://via.placeholder.com/150", true, 83 },
                    { 263, "https://via.placeholder.com/150", true, 83 },
                    { 230, "https://via.placeholder.com/150", true, 83 },
                    { 121, "https://via.placeholder.com/150", true, 83 },
                    { 54, "https://via.placeholder.com/150", true, 8 },
                    { 73, "https://via.placeholder.com/150", true, 83 },
                    { 87, "https://via.placeholder.com/150", true, 8 },
                    { 60, "https://via.placeholder.com/150", true, 12 },
                    { 391, "https://via.placeholder.com/150", true, 41 },
                    { 304, "https://via.placeholder.com/150", true, 41 },
                    { 236, "https://via.placeholder.com/150", true, 41 },
                    { 183, "https://via.placeholder.com/150", true, 41 },
                    { 91, "https://via.placeholder.com/150", true, 41 },
                    { 349, "https://via.placeholder.com/150", true, 37 },
                    { 287, "https://via.placeholder.com/150", true, 37 },
                    { 283, "https://via.placeholder.com/150", true, 37 },
                    { 280, "https://via.placeholder.com/150", true, 37 },
                    { 70, "https://via.placeholder.com/150", true, 37 },
                    { 59, "https://via.placeholder.com/150", true, 37 },
                    { 386, "https://via.placeholder.com/150", true, 28 },
                    { 298, "https://via.placeholder.com/150", true, 28 },
                    { 253, "https://via.placeholder.com/150", true, 28 },
                    { 110, "https://via.placeholder.com/150", true, 28 },
                    { 341, "https://via.placeholder.com/150", true, 21 },
                    { 180, "https://via.placeholder.com/150", true, 21 },
                    { 375, "https://via.placeholder.com/150", true, 20 },
                    { 118, "https://via.placeholder.com/150", true, 20 },
                    { 300, "https://via.placeholder.com/150", true, 15 },
                    { 177, "https://via.placeholder.com/150", true, 15 },
                    { 185, "https://via.placeholder.com/150", true, 8 },
                    { 76, "https://via.placeholder.com/150", true, 45 },
                    { 29, "https://via.placeholder.com/150", true, 83 },
                    { 377, "https://via.placeholder.com/150", true, 75 },
                    { 98, "https://via.placeholder.com/150", true, 46 },
                    { 39, "https://via.placeholder.com/150", true, 46 },
                    { 344, "https://via.placeholder.com/150", true, 39 },
                    { 227, "https://via.placeholder.com/150", true, 39 },
                    { 199, "https://via.placeholder.com/150", true, 39 },
                    { 169, "https://via.placeholder.com/150", true, 39 },
                    { 24, "https://via.placeholder.com/150", true, 39 },
                    { 20, "https://via.placeholder.com/150", true, 39 },
                    { 2, "https://via.placeholder.com/150", true, 39 },
                    { 313, "https://via.placeholder.com/150", true, 35 },
                    { 282, "https://via.placeholder.com/150", true, 35 },
                    { 170, "https://via.placeholder.com/150", true, 35 },
                    { 79, "https://via.placeholder.com/150", true, 35 },
                    { 336, "https://via.placeholder.com/150", true, 27 },
                    { 378, "https://via.placeholder.com/150", true, 6 },
                    { 345, "https://via.placeholder.com/150", true, 6 },
                    { 233, "https://via.placeholder.com/150", true, 6 },
                    { 158, "https://via.placeholder.com/150", true, 6 },
                    { 106, "https://via.placeholder.com/150", true, 6 },
                    { 83, "https://via.placeholder.com/150", true, 6 },
                    { 373, "https://via.placeholder.com/150", true, 2 },
                    { 374, "https://via.placeholder.com/150", true, 46 },
                    { 389, "https://via.placeholder.com/150", true, 75 },
                    { 58, "https://via.placeholder.com/150", true, 52 },
                    { 57, "https://via.placeholder.com/150", true, 54 },
                    { 258, "https://via.placeholder.com/150", true, 75 },
                    { 159, "https://via.placeholder.com/150", true, 75 },
                    { 154, "https://via.placeholder.com/150", true, 75 },
                    { 146, "https://via.placeholder.com/150", true, 75 },
                    { 107, "https://via.placeholder.com/150", true, 75 },
                    { 96, "https://via.placeholder.com/150", true, 75 },
                    { 270, "https://via.placeholder.com/150", true, 68 },
                    { 264, "https://via.placeholder.com/150", true, 68 },
                    { 321, "https://via.placeholder.com/150", true, 65 },
                    { 211, "https://via.placeholder.com/150", true, 65 },
                    { 99, "https://via.placeholder.com/150", true, 65 },
                    { 30, "https://via.placeholder.com/150", true, 65 },
                    { 14, "https://via.placeholder.com/150", true, 65 },
                    { 398, "https://via.placeholder.com/150", true, 61 },
                    { 254, "https://via.placeholder.com/150", true, 61 },
                    { 330, "https://via.placeholder.com/150", true, 59 },
                    { 210, "https://via.placeholder.com/150", true, 59 },
                    { 193, "https://via.placeholder.com/150", true, 59 },
                    { 52, "https://via.placeholder.com/150", true, 59 },
                    { 22, "https://via.placeholder.com/150", true, 59 },
                    { 251, "https://via.placeholder.com/150", true, 54 },
                    { 209, "https://via.placeholder.com/150", true, 52 },
                    { 178, "https://via.placeholder.com/150", true, 45 },
                    { 206, "https://via.placeholder.com/150", true, 45 },
                    { 228, "https://via.placeholder.com/150", true, 45 },
                    { 144, "https://via.placeholder.com/150", true, 9 },
                    { 34, "https://via.placeholder.com/150", true, 9 },
                    { 360, "https://via.placeholder.com/150", true, 5 },
                    { 248, "https://via.placeholder.com/150", true, 5 },
                    { 381, "https://via.placeholder.com/150", true, 4 },
                    { 354, "https://via.placeholder.com/150", true, 4 },
                    { 329, "https://via.placeholder.com/150", true, 4 },
                    { 328, "https://via.placeholder.com/150", true, 4 },
                    { 207, "https://via.placeholder.com/150", true, 4 },
                    { 45, "https://via.placeholder.com/150", true, 4 },
                    { 4, "https://via.placeholder.com/150", true, 4 },
                    { 212, "https://via.placeholder.com/150", true, 98 },
                    { 179, "https://via.placeholder.com/150", true, 98 },
                    { 116, "https://via.placeholder.com/150", true, 98 },
                    { 13, "https://via.placeholder.com/150", true, 98 },
                    { 399, "https://via.placeholder.com/150", true, 94 },
                    { 396, "https://via.placeholder.com/150", true, 94 },
                    { 122, "https://via.placeholder.com/150", true, 94 },
                    { 108, "https://via.placeholder.com/150", true, 94 },
                    { 265, "https://via.placeholder.com/150", true, 90 },
                    { 257, "https://via.placeholder.com/150", true, 90 },
                    { 149, "https://via.placeholder.com/150", true, 9 },
                    { 237, "https://via.placeholder.com/150", true, 90 },
                    { 215, "https://via.placeholder.com/150", true, 9 },
                    { 351, "https://via.placeholder.com/150", true, 9 },
                    { 319, "https://via.placeholder.com/150", true, 40 },
                    { 279, "https://via.placeholder.com/150", true, 40 },
                    { 256, "https://via.placeholder.com/150", true, 40 },
                    { 196, "https://via.placeholder.com/150", true, 40 },
                    { 160, "https://via.placeholder.com/150", true, 40 },
                    { 119, "https://via.placeholder.com/150", true, 40 },
                    { 244, "https://via.placeholder.com/150", true, 34 },
                    { 145, "https://via.placeholder.com/150", true, 34 },
                    { 138, "https://via.placeholder.com/150", true, 34 },
                    { 94, "https://via.placeholder.com/150", true, 34 },
                    { 312, "https://via.placeholder.com/150", true, 25 },
                    { 11, "https://via.placeholder.com/150", true, 25 },
                    { 333, "https://via.placeholder.com/150", true, 22 },
                    { 317, "https://via.placeholder.com/150", true, 22 },
                    { 325, "https://via.placeholder.com/150", true, 18 },
                    { 194, "https://via.placeholder.com/150", true, 18 },
                    { 331, "https://via.placeholder.com/150", true, 17 },
                    { 245, "https://via.placeholder.com/150", true, 17 },
                    { 113, "https://via.placeholder.com/150", true, 17 },
                    { 71, "https://via.placeholder.com/150", true, 17 },
                    { 356, "https://via.placeholder.com/150", true, 9 },
                    { 249, "https://via.placeholder.com/150", true, 9 },
                    { 202, "https://via.placeholder.com/150", true, 90 },
                    { 136, "https://via.placeholder.com/150", true, 90 },
                    { 275, "https://via.placeholder.com/150", true, 89 },
                    { 148, "https://via.placeholder.com/150", true, 70 },
                    { 51, "https://via.placeholder.com/150", true, 70 },
                    { 214, "https://via.placeholder.com/150", true, 55 },
                    { 105, "https://via.placeholder.com/150", true, 55 },
                    { 123, "https://via.placeholder.com/150", true, 53 },
                    { 37, "https://via.placeholder.com/150", true, 53 },
                    { 385, "https://via.placeholder.com/150", true, 51 },
                    { 150, "https://via.placeholder.com/150", true, 51 },
                    { 130, "https://via.placeholder.com/150", true, 51 },
                    { 7, "https://via.placeholder.com/150", true, 51 },
                    { 355, "https://via.placeholder.com/150", true, 50 },
                    { 314, "https://via.placeholder.com/150", true, 50 },
                    { 291, "https://via.placeholder.com/150", true, 50 },
                    { 286, "https://via.placeholder.com/150", true, 50 },
                    { 198, "https://via.placeholder.com/150", true, 50 },
                    { 174, "https://via.placeholder.com/150", true, 50 },
                    { 315, "https://via.placeholder.com/150", true, 49 },
                    { 246, "https://via.placeholder.com/150", true, 49 },
                    { 128, "https://via.placeholder.com/150", true, 49 },
                    { 95, "https://via.placeholder.com/150", true, 49 },
                    { 288, "https://via.placeholder.com/150", true, 45 },
                    { 176, "https://via.placeholder.com/150", true, 70 },
                    { 101, "https://via.placeholder.com/150", true, 74 },
                    { 204, "https://via.placeholder.com/150", true, 74 },
                    { 247, "https://via.placeholder.com/150", true, 74 },
                    { 273, "https://via.placeholder.com/150", true, 89 },
                    { 216, "https://via.placeholder.com/150", true, 89 },
                    { 140, "https://via.placeholder.com/150", true, 89 },
                    { 120, "https://via.placeholder.com/150", true, 89 },
                    { 68, "https://via.placeholder.com/150", true, 89 },
                    { 259, "https://via.placeholder.com/150", true, 87 },
                    { 250, "https://via.placeholder.com/150", true, 87 },
                    { 235, "https://via.placeholder.com/150", true, 87 },
                    { 147, "https://via.placeholder.com/150", true, 84 },
                    { 23, "https://via.placeholder.com/150", true, 84 },
                    { 337, "https://via.placeholder.com/150", true, 97 },
                    { 5, "https://via.placeholder.com/150", true, 84 },
                    { 129, "https://via.placeholder.com/150", true, 81 },
                    { 109, "https://via.placeholder.com/150", true, 81 },
                    { 43, "https://via.placeholder.com/150", true, 81 },
                    { 387, "https://via.placeholder.com/150", true, 80 },
                    { 347, "https://via.placeholder.com/150", true, 80 },
                    { 335, "https://via.placeholder.com/150", true, 80 },
                    { 192, "https://via.placeholder.com/150", true, 80 },
                    { 143, "https://via.placeholder.com/150", true, 80 },
                    { 6, "https://via.placeholder.com/150", true, 80 },
                    { 366, "https://via.placeholder.com/150", true, 74 },
                    { 218, "https://via.placeholder.com/150", true, 81 },
                    { 395, "https://via.placeholder.com/150", true, 97 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Product_CategoryId",
                table: "Product",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductImages_ProductID",
                table: "ProductImages",
                column: "ProductID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProductImages");

            migrationBuilder.DropTable(
                name: "Product");

            migrationBuilder.DropTable(
                name: "Category");
        }
    }
}
